// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	SessionID            string               `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	MemberID             string               `protobuf:"bytes,2,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	GatewayAddr          string               `protobuf:"bytes,3,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	Lastseen             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Lastseen,proto3" json:"Lastseen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{0}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (dst *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(dst, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Route) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *Route) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

func (m *Route) GetLastseen() *timestamp.Timestamp {
	if m != nil {
		return m.Lastseen
	}
	return nil
}

type RouteRequest struct {
	MemberIDs            []string `protobuf:"bytes,1,rep,name=MemberIDs,proto3" json:"MemberIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteRequest) Reset()         { *m = RouteRequest{} }
func (m *RouteRequest) String() string { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()    {}
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{1}
}
func (m *RouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteRequest.Unmarshal(m, b)
}
func (m *RouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteRequest.Marshal(b, m, deterministic)
}
func (dst *RouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteRequest.Merge(dst, src)
}
func (m *RouteRequest) XXX_Size() int {
	return xxx_messageInfo_RouteRequest.Size(m)
}
func (m *RouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteRequest proto.InternalMessageInfo

func (m *RouteRequest) GetMemberIDs() []string {
	if m != nil {
		return m.MemberIDs
	}
	return nil
}

type RouteReply struct {
	Routes               []*Route `protobuf:"bytes,1,rep,name=Routes,proto3" json:"Routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteReply) Reset()         { *m = RouteReply{} }
func (m *RouteReply) String() string { return proto.CompactTextString(m) }
func (*RouteReply) ProtoMessage()    {}
func (*RouteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{2}
}
func (m *RouteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteReply.Unmarshal(m, b)
}
func (m *RouteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteReply.Marshal(b, m, deterministic)
}
func (dst *RouteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteReply.Merge(dst, src)
}
func (m *RouteReply) XXX_Size() int {
	return xxx_messageInfo_RouteReply.Size(m)
}
func (m *RouteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteReply.DiscardUnknown(m)
}

var xxx_messageInfo_RouteReply proto.InternalMessageInfo

func (m *RouteReply) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type DeleteSessionRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{3}
}
func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(dst, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

func (m *DeleteSessionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type CreateOrUpdateRouteRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	MemberID             string   `protobuf:"bytes,2,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	GatewayAddr          string   `protobuf:"bytes,3,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateRouteRequest) Reset()         { *m = CreateOrUpdateRouteRequest{} }
func (m *CreateOrUpdateRouteRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateRouteRequest) ProtoMessage()    {}
func (*CreateOrUpdateRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{4}
}
func (m *CreateOrUpdateRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateRouteRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateRouteRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateRouteRequest.Merge(dst, src)
}
func (m *CreateOrUpdateRouteRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateRouteRequest.Size(m)
}
func (m *CreateOrUpdateRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateRouteRequest proto.InternalMessageInfo

func (m *CreateOrUpdateRouteRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateOrUpdateRouteRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *CreateOrUpdateRouteRequest) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{5}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_3b9877e5d92f698f, []int{6}
}
func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (dst *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(dst, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Route)(nil), "proto.Route")
	proto.RegisterType((*RouteRequest)(nil), "proto.RouteRequest")
	proto.RegisterType((*RouteReply)(nil), "proto.RouteReply")
	proto.RegisterType((*DeleteSessionRequest)(nil), "proto.DeleteSessionRequest")
	proto.RegisterType((*CreateOrUpdateRouteRequest)(nil), "proto.CreateOrUpdateRouteRequest")
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterServiceClient interface {
	Routes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteReply, error)
	CreateOrUpdateRoute(ctx context.Context, in *CreateOrUpdateRouteRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*EmptyReply, error)
}

type routerServiceClient struct {
	cc *grpc.ClientConn
}

func NewRouterServiceClient(cc *grpc.ClientConn) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) Routes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteReply, error) {
	out := new(RouteReply)
	err := c.cc.Invoke(ctx, "/proto.RouterService/Routes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) CreateOrUpdateRoute(ctx context.Context, in *CreateOrUpdateRouteRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/proto.RouterService/CreateOrUpdateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/proto.RouterService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
type RouterServiceServer interface {
	Routes(context.Context, *RouteRequest) (*RouteReply, error)
	CreateOrUpdateRoute(context.Context, *CreateOrUpdateRouteRequest) (*EmptyReply, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*EmptyReply, error)
}

func RegisterRouterServiceServer(s *grpc.Server, srv RouterServiceServer) {
	s.RegisterService(&_RouterService_serviceDesc, srv)
}

func _RouterService_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouterService/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).Routes(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_CreateOrUpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).CreateOrUpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouterService/CreateOrUpdateRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).CreateOrUpdateRoute(ctx, req.(*CreateOrUpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouterService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Routes",
			Handler:    _RouterService_Routes_Handler,
		},
		{
			MethodName: "CreateOrUpdateRoute",
			Handler:    _RouterService_CreateOrUpdateRoute_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _RouterService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_router_3b9877e5d92f698f) }

var fileDescriptor_router_3b9877e5d92f698f = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa9, 0x08, 0x81, 0xa1, 0x98, 0x38, 0x78, 0x68, 0xaa, 0x89, 0x75, 0xe3, 0x81, 0x83,
	0x29, 0x49, 0x35, 0xde, 0x89, 0x18, 0x43, 0x22, 0x31, 0x29, 0xfa, 0x00, 0x45, 0x46, 0x42, 0xd2,
	0xd2, 0x75, 0x77, 0x51, 0xfb, 0x2c, 0x3e, 0x97, 0xef, 0x63, 0xd8, 0x6e, 0x0b, 0x18, 0x38, 0x7a,
	0xda, 0xcc, 0x3f, 0xff, 0xce, 0x7c, 0xf3, 0x83, 0x2d, 0xd2, 0xa5, 0x22, 0xe1, 0x73, 0x91, 0xaa,
	0x14, 0x6b, 0xfa, 0x71, 0xcf, 0x67, 0x69, 0x3a, 0x8b, 0xa9, 0xa7, 0xab, 0xc9, 0xf2, 0xad, 0xa7,
	0xe6, 0x09, 0x49, 0x15, 0x25, 0x3c, 0xf7, 0xb1, 0x6f, 0x0b, 0x6a, 0xe1, 0xea, 0x23, 0x9e, 0x41,
	0x73, 0x4c, 0x52, 0xce, 0xd3, 0xc5, 0x70, 0xe0, 0x58, 0x9e, 0xd5, 0x6d, 0x86, 0x6b, 0x01, 0x5d,
	0x68, 0x8c, 0x28, 0x99, 0x90, 0x18, 0x0e, 0x9c, 0x03, 0xdd, 0x2c, 0x6b, 0xf4, 0xa0, 0xf5, 0x10,
	0x29, 0xfa, 0x8c, 0xb2, 0xfe, 0x74, 0x2a, 0x9c, 0xaa, 0x6e, 0x6f, 0x4a, 0x78, 0x0b, 0x8d, 0xc7,
	0x48, 0x2a, 0x49, 0xb4, 0x70, 0x0e, 0x3d, 0xab, 0xdb, 0x0a, 0x5c, 0x3f, 0x27, 0xf3, 0x0b, 0x32,
	0xff, 0xb9, 0x20, 0x0b, 0x4b, 0x2f, 0xbb, 0x02, 0x5b, 0xc3, 0x85, 0xf4, 0xbe, 0x24, 0xa9, 0x56,
	0x8c, 0xc5, 0x56, 0xe9, 0x58, 0x5e, 0x75, 0xc5, 0x58, 0x0a, 0x2c, 0x00, 0x30, 0x6e, 0x1e, 0x67,
	0x78, 0x09, 0x75, 0x5d, 0xe5, 0xc6, 0x56, 0x60, 0xe7, 0xab, 0xfc, 0xdc, 0x62, 0x7a, 0xec, 0x06,
	0x4e, 0x06, 0x14, 0x93, 0x22, 0x73, 0xea, 0xc6, 0xa6, 0xfd, 0x69, 0xb0, 0x2f, 0x70, 0xef, 0x04,
	0x45, 0x8a, 0x9e, 0xc4, 0x0b, 0x9f, 0x46, 0x8a, 0xfe, 0x52, 0xfe, 0x57, 0x92, 0xec, 0x08, 0xec,
	0xfb, 0x84, 0xab, 0xcc, 0xec, 0x62, 0x36, 0x80, 0xa9, 0x79, 0x9c, 0x05, 0x3f, 0x16, 0xb4, 0x35,
	0x8a, 0x18, 0x93, 0xf8, 0x98, 0xbf, 0x12, 0x06, 0x45, 0x0a, 0xd8, 0xd9, 0xba, 0x3f, 0xff, 0xee,
	0x1e, 0x6f, 0x8b, 0x3c, 0xce, 0x58, 0x05, 0x47, 0xd0, 0xd9, 0x71, 0x1d, 0x5e, 0x18, 0xef, 0xfe,
	0xcb, 0xcb, 0x71, 0x6b, 0x24, 0x56, 0xc1, 0x3e, 0xb4, 0xb7, 0x22, 0xc6, 0x53, 0xe3, 0xda, 0x15,
	0xfc, 0xce, 0x11, 0x93, 0xba, 0xd6, 0xae, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x8b, 0x82,
	0x5a, 0xe4, 0x02, 0x00, 0x00,
}
