// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/chatroom/proto/chatroom.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatroomCommand struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	SenderID             string   `protobuf:"bytes,2,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	SenderFirstName      string   `protobuf:"bytes,3,opt,name=SenderFirstName,proto3" json:"SenderFirstName,omitempty"`
	SenderLastName       string   `protobuf:"bytes,4,opt,name=SenderLastName,proto3" json:"SenderLastName,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatroomCommand) Reset()         { *m = ChatroomCommand{} }
func (m *ChatroomCommand) String() string { return proto.CompactTextString(m) }
func (*ChatroomCommand) ProtoMessage()    {}
func (*ChatroomCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatroom_11f5d0ebe765072b, []int{0}
}
func (m *ChatroomCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatroomCommand.Unmarshal(m, b)
}
func (m *ChatroomCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatroomCommand.Marshal(b, m, deterministic)
}
func (dst *ChatroomCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatroomCommand.Merge(dst, src)
}
func (m *ChatroomCommand) XXX_Size() int {
	return xxx_messageInfo_ChatroomCommand.Size(m)
}
func (m *ChatroomCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatroomCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChatroomCommand proto.InternalMessageInfo

func (m *ChatroomCommand) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *ChatroomCommand) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *ChatroomCommand) GetSenderFirstName() string {
	if m != nil {
		return m.SenderFirstName
	}
	return ""
}

func (m *ChatroomCommand) GetSenderLastName() string {
	if m != nil {
		return m.SenderLastName
	}
	return ""
}

func (m *ChatroomCommand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatroomCommand)(nil), "proto.ChatroomCommand")
}

func init() {
	proto.RegisterFile("pkg/chatroom/proto/chatroom.proto", fileDescriptor_chatroom_11f5d0ebe765072b)
}

var fileDescriptor_chatroom_11f5d0ebe765072b = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0xc8, 0x4e, 0xd7,
	0x4f, 0xce, 0x48, 0x2c, 0x29, 0xca, 0xcf, 0xcf, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x73,
	0xf5, 0xc0, 0x5c, 0x21, 0x56, 0x30, 0xa5, 0xb4, 0x9a, 0x91, 0x8b, 0xdf, 0x19, 0x2a, 0xe3, 0x9c,
	0x9f, 0x9b, 0x9b, 0x98, 0x97, 0x22, 0x24, 0xc6, 0xc5, 0x16, 0x94, 0x9f, 0x9f, 0xeb, 0xe9, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x09, 0x49, 0x71, 0x71, 0x04, 0xa7, 0xe6, 0xa5,
	0xa4, 0x16, 0x79, 0xba, 0x48, 0x30, 0x81, 0x65, 0xe0, 0x7c, 0x21, 0x0d, 0x2e, 0x7e, 0x08, 0xdb,
	0x2d, 0xb3, 0xa8, 0xb8, 0xc4, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x19, 0xac, 0x04, 0x5d, 0x58, 0x48,
	0x8d, 0x8b, 0x0f, 0x22, 0xe4, 0x93, 0x08, 0x55, 0xc8, 0x02, 0x56, 0x88, 0x26, 0x2a, 0x24, 0xc4,
	0xc5, 0xe2, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x27, 0xb1,
	0x81, 0x1d, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x0b, 0xa3, 0x9f, 0xe0, 0x00, 0x00,
	0x00,
}
