// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/gateway/proto/gateway.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendJobRequest struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=Jobs,proto3" json:"Jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJobRequest) Reset()         { *m = SendJobRequest{} }
func (m *SendJobRequest) String() string { return proto.CompactTextString(m) }
func (*SendJobRequest) ProtoMessage()    {}
func (*SendJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_dd03093b87f90fe7, []int{0}
}
func (m *SendJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJobRequest.Unmarshal(m, b)
}
func (m *SendJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJobRequest.Marshal(b, m, deterministic)
}
func (dst *SendJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJobRequest.Merge(dst, src)
}
func (m *SendJobRequest) XXX_Size() int {
	return xxx_messageInfo_SendJobRequest.Size(m)
}
func (m *SendJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendJobRequest proto.InternalMessageInfo

func (m *SendJobRequest) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Job struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	TargetID             string   `protobuf:"bytes,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_dd03093b87f90fe7, []int{1}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetTargetID() string {
	if m != nil {
		return m.TargetID
	}
	return ""
}

func (m *Job) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_dd03093b87f90fe7, []int{2}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_dd03093b87f90fe7, []int{3}
}
func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (dst *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(dst, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendJobRequest)(nil), "proto.SendJobRequest")
	proto.RegisterType((*Job)(nil), "proto.Job")
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	SendJobs(ctx context.Context, in *SendJobRequest, opts ...grpc.CallOption) (*EmptyReply, error)
}

type gatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayServiceClient(cc *grpc.ClientConn) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) SendJobs(ctx context.Context, in *SendJobRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/proto.GatewayService/SendJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	SendJobs(context.Context, *SendJobRequest) (*EmptyReply, error)
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_SendJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GatewayService/SendJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendJobs(ctx, req.(*SendJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendJobs",
			Handler:    _GatewayService_SendJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/gateway/proto/gateway.proto",
}

func init() {
	proto.RegisterFile("pkg/gateway/proto/gateway.proto", fileDescriptor_gateway_dd03093b87f90fe7)
}

var fileDescriptor_gateway_dd03093b87f90fe7 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0xc8, 0x4e, 0xd7,
	0x4f, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf1, 0xf4,
	0xc0, 0x3c, 0x21, 0x56, 0x30, 0xa5, 0x64, 0xc0, 0xc5, 0x17, 0x9c, 0x9a, 0x97, 0xe2, 0x95, 0x9f,
	0x14, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc7, 0xc5, 0xe2, 0x95, 0x9f, 0x54, 0x2c,
	0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0x05, 0x51, 0xae, 0x07, 0x52, 0x00, 0x16, 0x57, 0xf2,
	0xe4, 0x62, 0xf6, 0xca, 0x4f, 0x12, 0x12, 0xe2, 0x62, 0x09, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xa4, 0xb8, 0x38, 0x42, 0x12, 0x8b, 0xd2, 0x53, 0x4b,
	0x3c, 0x5d, 0x24, 0x98, 0xc0, 0xe2, 0x70, 0x3e, 0x48, 0xbd, 0x4b, 0x62, 0x49, 0xa2, 0x04, 0xb3,
	0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0xad, 0xc4, 0xc7, 0xc5, 0xe3, 0x9a, 0x5b, 0x50, 0x52, 0x09,
	0xb5, 0x5a, 0x89, 0x87, 0x8b, 0x0b, 0xca, 0x2f, 0xc8, 0xa9, 0x34, 0xf2, 0xe0, 0xe2, 0x73, 0x87,
	0x38, 0x39, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x8c, 0x8b, 0x03, 0xea, 0xd8, 0x62,
	0x21, 0x51, 0xa8, 0xc3, 0x50, 0x5d, 0x2f, 0x25, 0x08, 0x15, 0x46, 0x98, 0xa3, 0xc4, 0x90, 0xc4,
	0x06, 0x16, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xba, 0x90, 0x55, 0x15, 0x01, 0x00,
	0x00,
}
