// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/gateway/proto/gateway.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendCommandRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetID             string   `protobuf:"bytes,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCommandRequest) Reset()         { *m = SendCommandRequest{} }
func (m *SendCommandRequest) String() string { return proto.CompactTextString(m) }
func (*SendCommandRequest) ProtoMessage()    {}
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_466e3c2300fc2c99, []int{0}
}
func (m *SendCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCommandRequest.Unmarshal(m, b)
}
func (m *SendCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCommandRequest.Marshal(b, m, deterministic)
}
func (dst *SendCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCommandRequest.Merge(dst, src)
}
func (m *SendCommandRequest) XXX_Size() int {
	return xxx_messageInfo_SendCommandRequest.Size(m)
}
func (m *SendCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendCommandRequest proto.InternalMessageInfo

func (m *SendCommandRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SendCommandRequest) GetTargetID() string {
	if m != nil {
		return m.TargetID
	}
	return ""
}

func (m *SendCommandRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_466e3c2300fc2c99, []int{1}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_466e3c2300fc2c99, []int{2}
}
func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (dst *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(dst, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendCommandRequest)(nil), "proto.SendCommandRequest")
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*EmptyReply, error)
}

type gatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayServiceClient(cc *grpc.ClientConn) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/proto.GatewayService/SendCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	SendCommand(context.Context, *SendCommandRequest) (*EmptyReply, error)
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GatewayService/SendCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _GatewayService_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/gateway/proto/gateway.proto",
}

func init() {
	proto.RegisterFile("pkg/gateway/proto/gateway.proto", fileDescriptor_gateway_466e3c2300fc2c99)
}

var fileDescriptor_gateway_466e3c2300fc2c99 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0xc8, 0x4e, 0xd7,
	0x4f, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf1, 0xf4,
	0xc0, 0x3c, 0x21, 0x56, 0x30, 0xa5, 0x14, 0xc1, 0x25, 0x14, 0x9c, 0x9a, 0x97, 0xe2, 0x9c, 0x9f,
	0x9b, 0x9b, 0x98, 0x97, 0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc4, 0xc5, 0x52,
	0x52, 0x59, 0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x49, 0x71, 0x71,
	0x84, 0x24, 0x16, 0xa5, 0xa7, 0x96, 0x78, 0xba, 0x48, 0x30, 0x81, 0xc5, 0xe1, 0x7c, 0x90, 0x7a,
	0x97, 0xc4, 0x92, 0x44, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x5b, 0x89, 0x8f, 0x8b,
	0xc7, 0x35, 0xb7, 0xa0, 0xa4, 0x12, 0x6a, 0xa6, 0x12, 0x0f, 0x17, 0x17, 0x94, 0x5f, 0x90, 0x53,
	0x69, 0xe4, 0xcf, 0xc5, 0xe7, 0x0e, 0x71, 0x4f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90,
	0x2d, 0x17, 0x37, 0x92, 0x4b, 0x84, 0x24, 0x21, 0xee, 0xd4, 0xc3, 0x74, 0x9d, 0x94, 0x20, 0x54,
	0x0a, 0x61, 0x9c, 0x12, 0x43, 0x12, 0x1b, 0x58, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0xf2, 0x67, 0x97, 0xf9, 0x00, 0x00, 0x00,
}
