// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/gateway/proto/gateway.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandRequest struct {
	OP                   string   `protobuf:"bytes,1,opt,name=OP,proto3" json:"OP,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77b2370b0a6797e8, []int{0}
}
func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (dst *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(dst, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetOP() string {
	if m != nil {
		return m.OP
	}
	return ""
}

func (m *CommandRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommandReply struct {
	OP                   string   `protobuf:"bytes,1,opt,name=OP,proto3" json:"OP,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandReply) Reset()         { *m = CommandReply{} }
func (m *CommandReply) String() string { return proto.CompactTextString(m) }
func (*CommandReply) ProtoMessage()    {}
func (*CommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77b2370b0a6797e8, []int{1}
}
func (m *CommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandReply.Unmarshal(m, b)
}
func (m *CommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandReply.Marshal(b, m, deterministic)
}
func (dst *CommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandReply.Merge(dst, src)
}
func (m *CommandReply) XXX_Size() int {
	return xxx_messageInfo_CommandReply.Size(m)
}
func (m *CommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommandReply proto.InternalMessageInfo

func (m *CommandReply) GetOP() string {
	if m != nil {
		return m.OP
	}
	return ""
}

func (m *CommandReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetServerTimeReply struct {
	Time                 int64    `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServerTimeReply) Reset()         { *m = GetServerTimeReply{} }
func (m *GetServerTimeReply) String() string { return proto.CompactTextString(m) }
func (*GetServerTimeReply) ProtoMessage()    {}
func (*GetServerTimeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77b2370b0a6797e8, []int{2}
}
func (m *GetServerTimeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerTimeReply.Unmarshal(m, b)
}
func (m *GetServerTimeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerTimeReply.Marshal(b, m, deterministic)
}
func (dst *GetServerTimeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerTimeReply.Merge(dst, src)
}
func (m *GetServerTimeReply) XXX_Size() int {
	return xxx_messageInfo_GetServerTimeReply.Size(m)
}
func (m *GetServerTimeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerTimeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerTimeReply proto.InternalMessageInfo

func (m *GetServerTimeReply) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77b2370b0a6797e8, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CommandRequest)(nil), "proto.CommandRequest")
	proto.RegisterType((*CommandReply)(nil), "proto.CommandReply")
	proto.RegisterType((*GetServerTimeReply)(nil), "proto.GetServerTimeReply")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetServerTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServerTimeReply, error)
	CreateCommandStream(ctx context.Context, opts ...grpc.CallOption) (GatewayService_CreateCommandStreamClient, error)
}

type gatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayServiceClient(cc *grpc.ClientConn) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetServerTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServerTimeReply, error) {
	out := new(GetServerTimeReply)
	err := c.cc.Invoke(ctx, "/proto.GatewayService/GetServerTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateCommandStream(ctx context.Context, opts ...grpc.CallOption) (GatewayService_CreateCommandStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GatewayService_serviceDesc.Streams[0], "/proto.GatewayService/CreateCommandStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayServiceCreateCommandStreamClient{stream}
	return x, nil
}

type GatewayService_CreateCommandStreamClient interface {
	Send(*CommandRequest) error
	Recv() (*CommandReply, error)
	grpc.ClientStream
}

type gatewayServiceCreateCommandStreamClient struct {
	grpc.ClientStream
}

func (x *gatewayServiceCreateCommandStreamClient) Send(m *CommandRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayServiceCreateCommandStreamClient) Recv() (*CommandReply, error) {
	m := new(CommandReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	GetServerTime(context.Context, *Empty) (*GetServerTimeReply, error)
	CreateCommandStream(GatewayService_CreateCommandStreamServer) error
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_GetServerTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetServerTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GatewayService/GetServerTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetServerTime(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).CreateCommandStream(&gatewayServiceCreateCommandStreamServer{stream})
}

type GatewayService_CreateCommandStreamServer interface {
	Send(*CommandReply) error
	Recv() (*CommandRequest, error)
	grpc.ServerStream
}

type gatewayServiceCreateCommandStreamServer struct {
	grpc.ServerStream
}

func (x *gatewayServiceCreateCommandStreamServer) Send(m *CommandReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayServiceCreateCommandStreamServer) Recv() (*CommandRequest, error) {
	m := new(CommandRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerTime",
			Handler:    _GatewayService_GetServerTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateCommandStream",
			Handler:       _GatewayService_CreateCommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/gateway/proto/gateway.proto",
}

func init() {
	proto.RegisterFile("pkg/gateway/proto/gateway.proto", fileDescriptor_gateway_77b2370b0a6797e8)
}

var fileDescriptor_gateway_77b2370b0a6797e8 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0xc8, 0x4e, 0xd7,
	0x4f, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf1, 0xf4,
	0xc0, 0x3c, 0x21, 0x56, 0x30, 0xa5, 0x64, 0xc2, 0xc5, 0xe7, 0x9c, 0x9f, 0x9b, 0x9b, 0x98, 0x97,
	0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xc4, 0xc7, 0xc5, 0xe4, 0x1f, 0x20, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0xe4, 0x1f, 0x20, 0x24, 0xc4, 0xc5, 0xe2, 0x92, 0x58, 0x92, 0x28,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b, 0x19, 0x71, 0xf1, 0xc0, 0x75, 0x15, 0xe4,
	0x54, 0x12, 0xa5, 0x47, 0x83, 0x4b, 0xc8, 0x3d, 0xb5, 0x24, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0x28,
	0x24, 0x33, 0x37, 0x15, 0xa2, 0x53, 0x88, 0x8b, 0x05, 0xc4, 0x01, 0xeb, 0x65, 0x0e, 0x02, 0xb3,
	0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0xa6, 0x32, 0x72, 0xf1, 0xb9, 0x43,
	0x5c, 0x0d, 0xd2, 0x97, 0x99, 0x9c, 0x2a, 0x64, 0xc5, 0xc5, 0x8b, 0x62, 0x8a, 0x10, 0x0f, 0xc4,
	0x3f, 0x7a, 0x60, 0x1d, 0x52, 0x92, 0x50, 0x1e, 0xa6, 0x4d, 0x4a, 0x0c, 0x42, 0xee, 0x5c, 0xc2,
	0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x50, 0xb7, 0x07, 0x97, 0x14, 0xa5, 0x26, 0xe6, 0x0a, 0x89,
	0x42, 0xf5, 0xa0, 0x86, 0x83, 0x94, 0x30, 0xba, 0x30, 0xd8, 0x10, 0x0d, 0x46, 0x03, 0xc6, 0x24,
	0x36, 0xb0, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x0d, 0x8e, 0x38, 0x65, 0x01, 0x00,
	0x00,
}
